name: SubTV CLI

on: push

env:
  CI: true
  PNPM_CACHE_FOLDER: .pnpm-store

jobs:
  workflow:
    name: Lint, test, build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Git files setup
        uses: actions/checkout@v3

      - name: Node Setup
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - uses: pnpm/action-setup@v2.2.2
        name: Install pnpm
        with:
          version: 7
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install Dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Run Lint
        run: pnpm run lint

      - name: Run tests
        run: pnpm run test

      - name: Run tests
        run: pnpm run build

      - name: Run tests
        if: contains(github.ref, 'main')
        run: pnpm publish --no-git-checks -F @sub-tv/cli
