name: Node CI

on: push

jobs:
  lint:
    name: Linting
    env:
      CI: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Run Lint
        run: yarn lint
  build_cli:
    if: contains(github.ref, 'development') || contains(github.ref, 'master')
    name: Building CLI
    needs: lint
    env:
      CI: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Build
        working-directory: ./cli
        run: yarn build
