# name: Node CI

# on: push

# jobs:
#   lint:
#     name: ESLINT
#     runs-on: ubuntu-latest
#     steps:
#       run: |
#         yarn
#         cd cli
#         yarn lint

#   build_cli:
#     needs: lint
#     name: Build CLI
#     steps:
#       run: |
#         yarn
#         cd cli
#         yarn build

name: Greeting from Mona

on: push

jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
      - name: Print a greeting
        env:
          MY_VAR: Hi there! My name is
          FIRST_NAME: Mona
          MIDDLE_NAME: The
          LAST_NAME: Octocat
        run: |
          echo $MY_VAR $FIRST_NAME $MIDDLE_NAME $LAST_NAME.

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     strategy:
#       matrix:
#         node-version: [12.x]

#     steps:
#       - uses: actions/checkout@v1
#       - name: Use Node.js ${{ matrix.node-version }}
#         uses: actions/setup-node@v1
#         with:
#           node-version: ${{ matrix.node-version }}
#       - name: Install, lint, build and release check
#         run: |
#           yarn
#           yarn lint
#           yarn build
#           GH_TOKEN=${{ secrets.GH_TOKEN }} NPM_TOKEN=${{ secrets.NPM_TOKEN }} yarn release --branch=${GITHUB_REF##*/}
#         env:
#           CI: true
