name: Node CI

on: push

jobs:
  lint_and_test:
    name: Linting and Test
    env:
      CI: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Run Lint
        run: yarn lint
      - name: Run tests
        run: yarn test

  build:
    name: Building CLI
    env:
      CI: true
    needs: lint_and_test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Build
        run: yarn build

  release:
    name: Release new version
    if: contains(github.ref, 'master')
    needs: [lint_and_test, build]
    env:
      CI: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Release
        run: GH_TOKEN=${{ secrets.GH_TOKEN }} NPM_TOKEN=${{ secrets.NPM_TOKEN }} yarn release --branch=${GITHUB_REF##*/}
