# jobs:
#   lint:
#     name: ESLINT
#     runs-on: ubuntu-latest
#     steps:
#       run: |
#         yarn
#         cd cli
#         yarn lint

#   build_cli:
#     needs: lint
#     name: Build CLI
#     steps:
#       run: |
#         yarn
#         cd cli
#         yarn build

name: Node CI

on: push

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
      - name: Check code lint
        run: |
          yarn install
          yarn lint
        env:
          CI: true
  build_cli:
    needs: lint
    name: Build CLI
    steps:
      run: |
        cd cli
        yarn build
      env:
        CI: true
